Objects:
  - object_name: Table
    object_id: 0
    object_scale: 0.05
    object_position: [0,-7,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 1
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 1
    object_scale: 0.01
    object_position: [-1,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 2
    object_scale: 0.01
    object_position: [1,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 3
    object_scale: 0.01
    object_position: [0,-1,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 4
    object_scale: 0.01
    object_position: [0,1,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 5
    object_scale: 0.01
    object_position: [0,0,-1]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 6
    object_scale: 0.01
    object_position: [0,0,1]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: Sphere
    object_id: 7
    object_scale: 0.01
    object_position: [0,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [10,10,10]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [2]
    resource_graphics_pipeline_id: 0
  - object_name: cube
    object_id: 8
    object_scale: 1
    object_position: [0,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: true
    resource_model_id: 2
    resource_texture_id_list: [1]
    resource_graphics_pipeline_id: 1

Resources:
  - Models:
    - resource_model_name: sphere.obj
    - resource_model_name: ElegantTable.obj
    - resource_model_name: cube.obj
  - Textures:
    - resource_texture_name: repeat-pattern2.jpg
      resource_texture_miplevels: 9
      resource_texture_cubmap: false
      uniform_Sampler_id: 1
    - resource_texture_name: skybox_stormydays.jpg
      resource_texture_miplevels: 1
      resource_texture_cubmap: true
      uniform_Sampler_id: 0
    - resource_texture_name: metal.jpg
      resource_texture_miplevels: 1
      resource_texture_cubmap: false
      uniform_Sampler_id: 0
  - VertexShaders:
    - resource_vertexshader_name: shadowEnvironmentmap/environmentmap.vert.spv
    - resource_vertexshader_name: shadowEnvironmentmap/skybox.vert.spv
  - FragmentShaders:
    - resource_fragmentshader_name: shadowEnvironmentmap/environmentmap.frag.spv
    - resource_fragmentshader_name: shadowEnvironmentmap/skybox.frag.spv

Uniform:
  # Graphcis: CustomGraphics_MVP_VP
  Graphics: [[true, true, false]]
  # Compute: CustomCompute_Storage_SwapchainStorage_TextureStorage
  Compute: []
  # SamplerMiplevels: mipLevel0, mipLevel2, mipLevel3
  SamplerMiplevels: [1,9]

Feature:
  GraphicsDepthTest: true
  GraphicsMSAA: false
  Graphics48BPT: false
  GraphicsPushConstant: false
  GraphicsBlend: false
  GraphicsRainbowMipmap: false
  GraphicsPipelineSkyboxID: 1

MainCamera:
  FreeMode: true
  Position: [0,0,-3]
  Rotation: [0,0,0]
  TargetLocation: [0,0,0]
  FOV: 60
  Z: [0.01, 256]

Lighting:
  Position: []
  Intensity: []

  