Object:
  Models: [sphere.obj, ElegantChairTable.obj]
  Textures: [repeat-pattern2.jpg, skybox_stormydays.jpg, metal.jpg]
  TextureMiplevels: [9, 1, 1]
  TextureSamplers: [1, 0, 0] 
  TextureCubemap: [false, true, false]
  VertexShaders: [shadowEnvironmentmap/environmentmap.vert.spv, shadowEnvironmentmap/skybox.vert.spv]
  FragmentShaders: [shadowEnvironmentmap/environmentmap.frag.spv, shadowEnvironmentmap/skybox.frag.spv]
  ComputeShaders: []
  
  ModelList: [1, 0, 0, 0, 0, 0, 0, 0, 0]
  TextureList: [[0], [2], [2], [2], [2], [2], [2], [2], [1]]
  GraphicsPipelineList: [0, 0, 0, 0, 0, 0, 0, 0, 1]

Uniform:
  # Graphcis: CustomGraphics_MVP_VP
  Graphics: [[true, true, false]]
  # Compute: CustomCompute_Storage_SwapchainStorage_TextureStorage
  Compute: []
  # SamplerMiplevels: mipLevel0, mipLevel2, mipLevel3
  SamplerMiplevels: [1,9]

Feature:
  GraphicsDepthTest: true
  GraphicsMSAA: false
  Graphics48BPT: false
  GraphicsPushConstant: false
  GraphicsBlend: false
  GraphicsRainbowMipmap: false
  GraphicsPipelineSkyboxID: 1

MainCamera:
  FreeMode: true
  Position: [0,0,-3]
  Rotation: [0,0,0]
  TargetLocation: [0,0,0]
  FOV: 60
  Z: [0.01, 256]

Lighting:
  Position: []
  Intensity: []

  