Object:
  Models: [viking_room.obj, cube.obj]
  Textures: [viking_room.png, output_skybox.png, ]
  TextureMipmaps: [false, false]
  TextureCubemap: [false, true]
  VertexShaders: [simpleEnvironmentmap/environmentmap.vert.spv, simpleEnvironmentmap/skybox.vert.spv]
  FragmentShaders: [simpleEnvironmentmap/environmentmap.frag.spv, simpleEnvironmentmap/skybox.frag.spv]
  ComputeShaders: []
  
  ModelList: [1, 1]
  TextureList: [1, 1]
  GraphicsPipelineList: [0, 1]

Uniform:
  # Graphcis: CustomGraphics_MVP_VP
  Graphics: [[true, true, false]] #TODO
  # Sampler: SamplersNumber
  Sampler: [1]
  # Compute: CustomCompute_Storage_SwapchainStorage_TextureStorage (for now assume sample only need one compute pipeline)
  Compute: []

Feature:
  GraphicsDepthTest: true
  GraphicsMSAA: false
  Graphics48BPT: false
  GraphicsPushConstant: false
  GraphicsBlend: false
  GraphicsRainbowMipmap: false
  GraphicsPipelineSkyboxID: 1

MainCamera:
  FreeMode: true
  Position: [0,0,0]
  Rotation: [0,0,0]
  TargetLocation: [0,0,0]
  FOV: 60
  Z: [0.01, 256]

