Object:
  Models: [cube.obj]
  Textures: [skybox_interstellar.jpg]
  TextureMipmaps: [1]
  TextureSamplers: [0] 
  TextureCubemap: [true]
  VertexShaders: [simpleEnvironmentmap/environmentmap.vert.spv, simpleEnvironmentmap/skybox.vert.spv]
  FragmentShaders: [simpleEnvironmentmap/environmentmap.frag.spv, simpleEnvironmentmap/skybox.frag.spv]
  ComputeShaders: []
  
  ModelList: [0, 0, 0, 0, 0, 0, 0, 0]
  TextureList: [[0], [0], [0], [0], [0], [0], [0], [0]]
  GraphicsPipelineList: [0, 0, 0, 0, 0, 0, 0, 1]

Uniform:
  # Graphcis: CustomGraphics_MVP_VP
  Graphics: [[true, true, false]]
  # Compute: CustomCompute_Storage_SwapchainStorage_TextureStorage
  Compute: []
  # SamplerAttributes: mipLevel0, mipLevel2, mipLevel3
  SamplerAttributes: [1]

Feature:
  GraphicsDepthTest: true
  GraphicsMSAA: false
  Graphics48BPT: false
  GraphicsPushConstant: false
  GraphicsBlend: false
  GraphicsRainbowMipmap: false
  GraphicsPipelineSkyboxID: 1

MainCamera:
  FreeMode: true
  Position: [0,0,-3]
  Rotation: [0,0,0]
  TargetLocation: [0,0,0]
  FOV: 60
  Z: [0.01, 256]

